CREATE TABLE IF NOT EXISTS connections (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    group_path TEXT NOT NULL DEFAULT '',
    color TEXT,
    conn_type TEXT NOT NULL DEFAULT 'standalone',
    host TEXT NOT NULL DEFAULT 'localhost',
    port INTEGER NOT NULL DEFAULT 27017,
    auth_type TEXT NOT NULL DEFAULT 'none',
    username TEXT,
    password_encrypted TEXT,
    auth_db TEXT DEFAULT 'admin',
    replica_set TEXT,
    srv INTEGER NOT NULL DEFAULT 0,
    tls INTEGER NOT NULL DEFAULT 0,
    tls_ca_file TEXT,
    tls_cert_file TEXT,
    tls_key_file TEXT,
    tls_allow_invalid INTEGER NOT NULL DEFAULT 0,
    ssh_enabled INTEGER NOT NULL DEFAULT 0,
    ssh_host TEXT,
    ssh_port INTEGER DEFAULT 22,
    ssh_username TEXT,
    ssh_auth_type TEXT DEFAULT 'password',
    ssh_password_encrypted TEXT,
    ssh_private_key TEXT,
    ssh_passphrase_encrypted TEXT,
    default_db TEXT,
    uri_options TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_connections_group ON connections(group_path);
